--- Makefile	Tue Mar 28 14:23:58 2000
+++ Makefile	Fri Mar  2 11:51:15 2001
@@ -19,7 +19,7 @@
 ########## CHOOSE YOUR ARCHITECTURE:    (NOTE: also see bplaysrc/Makefile!)
 
 # For Linux (and maybe others), use these:
-CFLAGS = -g -Wall -O2 -DTURBO_MEDIAN -DTURBO_BUFFER
+CFLAGS = -g -Wall -O2 -funroll-loops -DTURBO_MEDIAN -DTURBO_BUFFER
 DEPS = $(OBJS) makebplay
 LIBS = -lncurses -lm
 COPY_A = -a
